name: Publish Docs

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/docs.yml
      - mkdocs.yml
      - docs/**
      - manage-docs

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Setup poetry
      uses: Gr1N/setup-poetry@v4
      with:
        poetry-version: 1.1.4

    - name: Install dependencies
      run: poetry install

    - name: Config git
      run: |
        git config --global user.name github-actions
        git config --global user.email ""

    - name: Publish docs
      run: poetry run ./manage-docs build dev
