name: Publish Docs

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/docs.yml
      - mkdocs.yml
      - docs/**

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Setup poetry
      uses: Gr1N/setup-poetry@v4
      with:
        poetry-version: 1.1.4

    - name: Cache virtualenv
      uses: actions/cache@v1
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Publish docs
      run: poetry run mkdocs gh-deploy
